name: Build Docker container image

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
    tags:
      - "v*"

env:
  IMAGE_NAME: ghcr.io/draggie306/norris

jobs:
  container:
    name: Container image
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v4
    
      - name: Login to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate image metadata
        id: meta
        uses: docker/metadata-action@v6
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=tag
            type=sha,prefix=sha-
            type=raw,value=latest,enable={{is_default_branch}}
          labels: |
            org.opencontainers.image.title=Norris
            org.opencontainers.image.description=Registration bot for the University of Nottingham's School of Computer Science servers. 
            org.opencontainers.image.source=https://github.com/Draggie306/norris

      - name: Generate database image metadata
        id: db-meta
        uses: docker/metadata-action@v6
        with:
          images: ghcr.io/draggie306/norris-db
          tags: |
            type=ref,event=tag
            type=sha,prefix=sha-
            type=raw,value=latest,enable={{is_default_branch}}
          labels: |
            org.opencontainers.image.title=Norris's database
            org.opencontainers.image.description=MySQL db containing the initial schema for Norris, the University of Nottingham's Computer Science registration bot.
            org.opencontainers.image.source=https://github.com/Draggie306/norris

      - name: Build and publish database image
        uses: docker/build-push-action@v7
        with:
          context: ./db
          file: ./db/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.db-meta.outputs.tags }}
          labels: ${{ steps.db-meta.outputs.labels }}
          cache-from: type=gha,scope=norris-db-v2
          cache-to: type=gha,scope=norris-db-v2,mode=max,ignore-error=true

      - name: Push and publish
        uses: docker/build-push-action@v7
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha,scope=norris_v2
          cache-to: type=gha,scope=norris_v2,mode=max,ignore-error=true
